name: check-default

on:
  pull_request:
  push:
    branches:
      - main
      - 7.1*
      - 8.*

permissions:
  contents: read
  pull-requests: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: .go-version
    - name: Run check-default
      run: |
        go install github.com/magefile/mage
        make check-default

  unified-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run check/update
      run: |
        #GO_VERSION=$(cat .go-version) ./dev-tools/run_with_go_ver make test-mage
        GO_VERSION='1.21.6' ./dev-tools/run_with_go_ver make test-mage
      env:
        GOFLAGS: '-mod=readonly'
